//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 211506359
//  @ File Name : StaticData.cpp
//  @ Date : 2017/9/29
//  @ Author : ∂°ø°»Ÿ
//
//


#include "StaticData.h"

StaticData* StaticData::sharedStaticData() {

}

void StaticData::purge() {

}

int StaticData::intValueForKey(const std::string &key) {

}

cont char* StaticData::stringValueFromKey(const std::string &key) {

}

float StaticData::floatValueFromKey(const std::string &key) {

}

bool StaticData::booleanFromKey(const std::string &key) {

}

cocos2d::CCPoint StaticData::pointFromKey(const std::string &key) {

}

cocos2d::CCRect StaticData::rectFromKey(const std::string &key) {

}

cocos2d::CCSize StaticData::sizeFormKey(const std::string &key) {

}

bool StaticData::init() {

}

StaticData::~StaticData() {

}

StaticData::StaticData() {

}

